"""Code generated by servicegen. DO NOT EDIT."""

from dataclasses import dataclass
from typing import Any

from pyservicelib_gorundebug.runtime.config import (
    DataConnectorConfig,
    EndpointConfig,
    InputStreamConfig,
    MergeStreamConfig,
    ProcessStreamConfig,
    ServiceAppConfig,
    ServiceConfig,
)


@dataclass(frozen=True, slots=True)
class Streams:
    get_inventory_item_data: ProcessStreamConfig
    merge_inventory_result: MergeStreamConfig
    process_inventory_item: InputStreamConfig


@dataclass(frozen=True, slots=True)
class Endpoints:
    process_order_item: EndpointConfig


@dataclass(frozen=True, slots=True)
class DataConnectors:
    inventory_service_api: DataConnectorConfig


@dataclass(frozen=True, slots=True)
class Services:
    inventory_service: ServiceConfig


@dataclass(frozen=True, slots=True)
class NamedConfig:
    streams: Streams
    endpoints: Endpoints
    data_connectors: DataConnectors
    services: Services


class GeneratedConfig(ServiceAppConfig):
    """Generated, typed view over the generic runtime graph configuration."""

    @classmethod
    def _load_config(cls, obj: dict[str, Any]) -> dict[str, Any]:
        def values(name: str) -> list[dict[str, Any]]:
            section = obj.get(name, {})
            return list(section.values()) if isinstance(section, dict) else section

        normalized = dict(obj)
        for name in ("services", "streams", "links", "types", "pools", "endpoints"):
            normalized[name] = values(name)
        normalized["dataConnectors"] = values("dataConnectors")
        return super()._load_config(normalized)

    @property
    def named(self) -> NamedConfig:
        return NamedConfig(
            streams=Streams(
                get_inventory_item_data=ProcessStreamConfig(
                    self.get_stream_config_by_id(1)
                ),
                merge_inventory_result=MergeStreamConfig(
                    self.get_stream_config_by_id(2)
                ),
                process_inventory_item=InputStreamConfig(
                    self.get_stream_config_by_id(3)
                ),
            ),
            endpoints=Endpoints(
                process_order_item=self.get_endpoint_config_by_id(1),
            ),
            data_connectors=DataConnectors(
                inventory_service_api=self.get_data_connector_by_id(1),
            ),
            services=Services(
                inventory_service=self.get_service_config_by_id(1),
            ),
        )
