[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "pyservicelib_gorundebug"
version = "0.2.75"
dynamic = ["dependencies"]
authors = [
    { name="Sergey Alexeev", email="sergeyalexeev@yahoo.com" },
]
description = "GoRunDebug.com service library for python"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/gorundebug/pyservicelib"
Issues = "https://github.com/gorundebug/pyservicelib/issues"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
[tool.hatch.build]
exclude = [
    "/.*", "/*.sh", "/*.json", "/diagram"
]
[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]
