# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime.

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CallSemantics(int, Enum):
    """
    Delivery semantics for a stream link — controls how messages are passed between nodes. - `Inherited` (1): use the service's `defaultCallSemantics` - `FunctionCall` (2): synchronous in-goroutine call; lowest latency, no buffering - `TaskPool` (3): enqueue to a named FIFO worker pool; decouples producer from consumer - `PriorityTaskPool` (4): enqueue to a named priority worker pool; higher-priority messages are processed first - `ParallelCall` (5): spawn a new goroutine for each message; fully parallel, no pool overhead
    """

    """
    allowed enum values
    """
    Undefined = 0
    Inherited = 1
    FunctionCall = 2
    TaskPool = 3
    PriorityTaskPool = 4
    ParallelCall = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CallSemantics from a JSON string"""
        return cls(json.loads(json_str))
