# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DataConnectorImplementation(str, Enum):
    """
    The specific library used to implement a data connector. - `net/http`: Go standard library HTTP - `function`: in-process custom connector (no network) - `IBM/Sarama`: Sarama Kafka client - `google/grpc`: official gRPC-Go library - `userver/http`: userver HTTP - `userver/grpc`: userver gRPC - `userver/kafka`: userver Kafka - `boost/beast-http`: Boost.Beast HTTP - `asio/grpc`: asio-grpc - `librdkafka`: librdkafka C++ client - `aiohttp`: Python aiohttp - `aiokafka`: Python aiokafka - `rust/axum`: Rust axum HTTP - `rust/tonic`: Rust tonic gRPC - `rust/rdkafka`: Rust rdkafka Kafka client - `node/http`: Node.js core HTTP transport - `grpc/grpc-js`: official pure-JavaScript gRPC transport - `confluent/kafka-javascript`: Confluent Kafka JavaScript client - `cpp/libcron`: libcron-backed UTC cron scheduler for C++ runtimes
    """

    """
    allowed enum values
    """
    Undefined = ''
    NetHTTP = 'net/http'
    Function = 'function'
    IBMsarama = 'IBM/Sarama'
    GoogleGRPC = 'google/grpc'
    UserverHTTP = 'userver/http'
    UserverGRPC = 'userver/grpc'
    UserverKafka = 'userver/kafka'
    BoostBeastHTTP = 'boost/beast-http'
    AsioGRPC = 'asio/grpc'
    Librdkafka = 'librdkafka'
    AioHTTP = 'aiohttp'
    AioKafka = 'aiokafka'
    RustAxum = 'rust/axum'
    RustTonic = 'rust/tonic'
    RustRdkafka = 'rust/rdkafka'
    NodeHTTP = 'node/http'
    GrpcJS = 'grpc/grpc-js'
    ConfluentKafkaJavaScript = 'confluent/kafka-javascript'
    GoGocron = 'go/gocron'
    PythonAPScheduler = 'python/apscheduler'
    RustCroner = 'rust/croner'
    NodeCroner = 'node/croner'
    CppLibcron = 'cpp/libcron'
    TemporalGo = 'temporal/go'
    TemporalPython = 'temporal/python'
    TemporalTypeScript = 'temporal/typescript'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataConnectorImplementation from a JSON string"""
        return cls(json.loads(json_str))
