# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from ..models.data_connector_implementation import DataConnectorImplementation
from ..models.data_connector_type import DataConnectorType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DataConnector(BaseModel):
    """
    Configuration for a connection to an external system. A data connector represents the external system itself (an HTTP server, a Kafka cluster, a gRPC server). Specific routes, topics, or methods are defined as `Endpoint` objects that reference this connector. 
    """ # noqa: E501
    id: StrictInt = Field(description="Unique identifier for this data connector within the topology.", json_schema_extra={"examples": [1]})
    name: StrictStr = Field(description="Human-readable connector name used in the visual designer and in generated server/client struct names.", json_schema_extra={"examples": ["KafkaCluster"]})
    type: DataConnectorType
    implementation: DataConnectorImplementation
    host: Optional[StrictStr] = Field(default=None, description="Hostname or IP address. Applies to HTTP and gRPC connectors.")
    port: Optional[Annotated[int, Field(le=65535, strict=True, ge=80)]] = Field(default=None, description="Port number. Applies to HTTP and gRPC connectors.")
    address: Optional[StrictStr] = Field(default=None, description="gRPC connection address.")
    brokers: Optional[StrictStr] = Field(default=None, description="Comma-separated list of Kafka broker addresses (e.g. `kafka1:9092,kafka2:9092`). Applies to Kafka connectors.")
    version: Optional[StrictStr] = Field(default=None, description="Kafka protocol version expected by the broker (e.g. `2.8.0`). Applies to Kafka connectors.")
    dial_timeout: Optional[Union[Annotated[float, Field(le=3600000, strict=True, ge=0)], Annotated[int, Field(le=3600000, strict=True, ge=0)]]] = Field(default=None, description="Connection dial timeout in milliseconds. Applies to Kafka connectors.", alias="dialTimeout")
    use_partitioner: Optional[StrictBool] = Field(default=None, description="When true, a custom Kafka partitioner is used for produced messages. The partitioner function is included in the generated stub. Applies to Kafka sink connectors. ", alias="usePartitioner")
    var_async: Optional[StrictBool] = Field(default=None, description="When true, the Kafka producer operates in async mode — messages are batched and acknowledged asynchronously. Applies to Kafka sink connectors. ", alias="async")
    use_dedicated_listener: Optional[StrictBool] = Field(default=None, description="When true, this HTTP connector starts its own dedicated `net/http` listener. When false, it shares the service's default HTTP mux. Applies to HTTP source connectors. ", alias="useDedicatedListener")
    module: Optional[StrictStr] = Field(default=None, description="Go module name containing the generated gRPC protobuf types for this connector. Used to resolve the correct import path for generated gRPC method stubs. Applies to gRPC connectors. ")
    __properties: ClassVar[List[str]] = ["id", "name", "type", "implementation", "host", "port", "address", "brokers", "version", "dialTimeout", "usePartitioner", "async", "useDedicatedListener", "module"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataConnector from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataConnector from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "implementation": obj.get("implementation"),
            "host": obj.get("host"),
            "port": obj.get("port"),
            "address": obj.get("address"),
            "brokers": obj.get("brokers"),
            "version": obj.get("version"),
            "dialTimeout": obj.get("dialTimeout"),
            "usePartitioner": obj.get("usePartitioner"),
            "async": obj.get("async"),
            "useDedicatedListener": obj.get("useDedicatedListener"),
            "module": obj.get("module")
        })
        return _obj


