# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DataType(str, Enum):
    """
    Primitive or composite data type for a named type. Controls generated serde code and type compatibility checks within the graph. Use `custom` for user-defined structs, `struct` for inline struct definitions, `array` for slices, `map` for maps, and `any` for untyped/interface values. 
    """

    """
    allowed enum values
    """
    Undefined = ''
    int = 'int'
    uint = 'uint'
    byte = 'byte'
    char = 'char'
    boolean = 'boolean'
    unicodeChar = 'unicode char'
    string = 'string'
    unicodeString = 'unicode string'
    float = 'float'
    double = 'double'
    int8 = 'int8'
    int16 = 'int16'
    int32 = 'int32'
    int64 = 'int64'
    uint8 = 'uint8'
    uint16 = 'uint16'
    uint32 = 'uint32'
    uint64 = 'uint64'
    any = 'any'
    error = 'error'
    array = 'array'
    map = 'map'
    struct = 'struct'
    custom = 'custom'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataType from a JSON string"""
        return cls(json.loads(json_str))


