# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DataConnectorImplementation(str, Enum):
    """
    The specific library used to implement a data connector. - `net/http`: Go standard library HTTP - `function`: in-process custom connector (no network) - `IBM/Sarama`: Sarama Kafka client - `google/grpc`: official gRPC-Go library 
    """

    """
    allowed enum values
    """
    Undefined = ''
    NetHTTP = 'net/http'
    Function = 'function'
    IBMsarama = 'IBM/Sarama'
    GoogleGRPC = 'google/grpc'
    UserverHTTP = 'userver/http'
    UserverGRPC = 'userver/grpc'
    UserverKafka = 'userver/kafka'
    AioHTTP = 'aiohttp'
    AioKafka = 'aiokafka'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataConnectorImplementation from a JSON string"""
        return cls(json.loads(json_str))

