# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DataConnectorType(int, Enum):
    """
    Type of external system the data connector connects to. - `HTTP` (1): HTTP server or client - `gRPC` (2): gRPC server or client - `Kafka` (3): Kafka cluster - `Custom` (4): in-process local connector for testing or internal pipelines 
    """

    """
    allowed enum values
    """
    Undefined = 0
    HTTP = 1
    gRPC = 2
    Kafka = 3
    Custom = 4

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataConnectorType from a JSON string"""
        return cls(json.loads(json_str))


