# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ..models.grpc_method_type import GrpcMethodType
from ..models.http_method_type import HTTPMethodType
from ..models.schedule_missed_run_policy import ScheduleMissedRunPolicy
from ..models.schedule_overlap_policy import ScheduleOverlapPolicy
from ..models.temporal_execution_type import TemporalExecutionType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Endpoint(BaseModel):
    """
    A specific entry or exit point on a data connector — an HTTP route, a Kafka topic, or a gRPC method. Each Input or Sink stream node references exactly one endpoint. The endpoint determines the handler interface that the code generator produces. 
    """ # noqa: E501
    id: StrictInt = Field(description="Unique identifier for this endpoint within the topology.", json_schema_extra={"examples": [1]})
    name: StrictStr = Field(description="Human-readable endpoint name shown in the visual designer.", json_schema_extra={"examples": ["IngestEndpoint"]})
    id_data_connector: StrictInt = Field(description="ID of the data connector this endpoint belongs to.", alias="idDataConnector", json_schema_extra={"examples": [1]})
    enabled: Optional[StrictBool] = Field(default=None, description="Controls whether an endpoint starts its transport integration. When omitted or false, the endpoint remains in the execution graph but its external transport or scheduler is not started. ")
    tracing_enabled: Optional[StrictBool] = Field(default=None, description="Enables tracing for events admitted by this DataSource endpoint. The current reloadable value is evaluated for every inbound event. DataSink adapters ignore this flag and only propagate tracing already present in the message context. ", alias="tracingEnabled")
    http_method_type: Optional[HTTPMethodType] = Field(default=None, alias="httpMethodType")
    path: Optional[StrictStr] = Field(default=None, description="URL path for HTTP endpoints (e.g. `/api/v1/orders`). Applies to HTTP connectors.")
    function_name: StrictStr = Field(description="Name of the generated Go handler struct for this endpoint.", alias="functionName")
    function_package: Optional[StrictStr] = Field(default=None, description="Subdirectory under the functions package where the generated handler is placed.", alias="functionPackage")
    public_function: Optional[StrictBool] = Field(default=None, description="When true, the generated handler is placed in the shared `pkg/functions` tree and can be imported by other services. When false, it goes into `internal/functions`. ", alias="publicFunction")
    function_description: Optional[StrictStr] = Field(default=None, description="Doc comment added to the generated handler struct.", alias="functionDescription")
    function_initializer_group: Optional[StrictStr] = Field(default=None, description="Initializer group for dependency injection of the generated handler.", alias="functionInitializerGroup")
    function_module: Optional[StrictStr] = Field(default=None, description="Name of a module defined in `StreamApp.modules`. When set (and `publicFunction: true`), the generated handler is placed in that module instead of the service module. ", alias="functionModule")
    topic: Optional[StrictStr] = Field(default=None, description="Kafka topic name. Applies to Kafka endpoints.")
    partitions: Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]] = Field(default=None, description="Number of partitions for the Kafka topic (used when createTopic is true).")
    create_topic: Optional[StrictBool] = Field(default=None, description="When true, the generated service attempts to create the Kafka topic on startup if it does not exist.", alias="createTopic")
    replication_factor: Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]] = Field(default=None, description="Kafka topic replication factor (used when createTopic is true).", alias="replicationFactor")
    consumer_group: Optional[StrictStr] = Field(default=None, description="Kafka consumer group ID. Applies to Kafka source endpoints.", alias="consumerGroup")
    grpc_method_type: Optional[GrpcMethodType] = Field(default=None, alias="grpcMethodType")
    method_name: Optional[StrictStr] = Field(default=None, description="gRPC method name as defined in the proto file. Applies to gRPC endpoints.", alias="methodName")
    schedule: Optional[StrictStr] = Field(default=None, description="Cron expression for a local Cron endpoint or an optional Temporal Schedule.")
    schedule_id: Optional[StrictStr] = Field(default=None, description="Immutable Temporal Schedule ID. Required when a Temporal endpoint has a schedule.", alias="scheduleId")
    timezone: Optional[StrictStr] = Field(default=None, description="Timezone used to evaluate the schedule. The portable contract accepts only UTC.")
    overlap_policy: Optional[ScheduleOverlapPolicy] = Field(default=None, alias="overlapPolicy")
    missed_run_policy: Optional[ScheduleMissedRunPolicy] = Field(default=None, alias="missedRunPolicy")
    task_queue: Optional[StrictStr] = Field(default=None, description="Temporal Task Queue used by this durable endpoint.", alias="taskQueue")
    temporal_execution_type: Optional[TemporalExecutionType] = Field(default=None, alias="temporalExecutionType")
    max_concurrent_activities: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum Activity Task executions for this endpoint's Task Queue. Applies to Activity endpoints.", alias="maxConcurrentActivities")
    max_concurrent_workflow_tasks: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum Workflow Task executions for this endpoint's Task Queue. Applies to Workflow endpoints; this does not limit open Workflow executions.", alias="maxConcurrentWorkflowTasks")
    workflow_execution_timeout: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Temporal Workflow execution timeout in milliseconds; zero means SDK default.", alias="workflowExecutionTimeout")
    activity_start_to_close_timeout: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Temporal Activity start-to-close timeout in milliseconds.", alias="activityStartToCloseTimeout")
    activity_heartbeat_timeout: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Temporal Activity heartbeat timeout in milliseconds; zero disables it.", alias="activityHeartbeatTimeout")
    maximum_attempts: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum Temporal Activity attempts including the initial attempt.", alias="maximumAttempts")
    __properties: ClassVar[List[str]] = ["id", "name", "idDataConnector", "enabled", "tracingEnabled", "httpMethodType", "path", "functionName", "functionPackage", "publicFunction", "functionDescription", "functionInitializerGroup", "functionModule", "topic", "partitions", "createTopic", "replicationFactor", "consumerGroup", "grpcMethodType", "methodName", "schedule", "scheduleId", "timezone", "overlapPolicy", "missedRunPolicy", "taskQueue", "temporalExecutionType", "maxConcurrentActivities", "maxConcurrentWorkflowTasks", "workflowExecutionTimeout", "activityStartToCloseTimeout", "activityHeartbeatTimeout", "maximumAttempts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Endpoint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Endpoint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "idDataConnector": obj.get("idDataConnector"),
            "enabled": obj.get("enabled"),
            "tracingEnabled": obj.get("tracingEnabled"),
            "httpMethodType": obj.get("httpMethodType"),
            "path": obj.get("path"),
            "functionName": obj.get("functionName"),
            "functionPackage": obj.get("functionPackage"),
            "publicFunction": obj.get("publicFunction"),
            "functionDescription": obj.get("functionDescription"),
            "functionInitializerGroup": obj.get("functionInitializerGroup"),
            "functionModule": obj.get("functionModule"),
            "topic": obj.get("topic"),
            "partitions": obj.get("partitions"),
            "createTopic": obj.get("createTopic"),
            "replicationFactor": obj.get("replicationFactor"),
            "consumerGroup": obj.get("consumerGroup"),
            "grpcMethodType": obj.get("grpcMethodType"),
            "methodName": obj.get("methodName"),
            "schedule": obj.get("schedule"),
            "scheduleId": obj.get("scheduleId"),
            "timezone": obj.get("timezone"),
            "overlapPolicy": obj.get("overlapPolicy"),
            "missedRunPolicy": obj.get("missedRunPolicy"),
            "taskQueue": obj.get("taskQueue"),
            "temporalExecutionType": obj.get("temporalExecutionType"),
            "maxConcurrentActivities": obj.get("maxConcurrentActivities"),
            "maxConcurrentWorkflowTasks": obj.get("maxConcurrentWorkflowTasks"),
            "workflowExecutionTimeout": obj.get("workflowExecutionTimeout"),
            "activityStartToCloseTimeout": obj.get("activityStartToCloseTimeout"),
            "activityHeartbeatTimeout": obj.get("activityHeartbeatTimeout"),
            "maximumAttempts": obj.get("maximumAttempts")
        })
        return _obj

