# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Environment(str, Enum):
    """
    Deployment environment for the service. Controls which observability engines are selected in the generated bootstrap code. - `local`: local developer machine; human-readable logs and tracing, Prometheus metrics - `debug`: same as local but with verbose/debug-level output - `staging`: pre-production; structured logs and tracing exported via OTLP, Prometheus metrics - `production`: live traffic; structured logs and tracing exported via OTLP, Prometheus metrics 
    """

    """
    allowed enum values
    """
    Undefined = ''
    Local = 'local'
    Debug = 'debug'
    Staging = 'staging'
    Production = 'production'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Environment from a JSON string"""
        return cls(json.loads(json_str))


