# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GrpcMethodType(int, Enum):
    """
    gRPC streaming mode for a gRPC endpoint. Determines the generated handler signature and the streaming behavior of the connector. - `NoStreaming` (1): unary RPC - `ClientStreaming` (2): client sends a stream, server replies once - `ServerStreaming` (4): client sends once, server replies with a stream - `BidirectionalStreaming` (5): both sides stream concurrently 
    """

    """
    allowed enum values
    """
    Undefined = 0
    NoStreaming = 1
    ClientStreaming = 2
    ServerStreaming = 4
    BidirectionalStreaming = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GrpcMethodType from a JSON string"""
        return cls(json.loads(json_str))


