# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ..models.call_semantics import CallSemantics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Link(BaseModel):
    """
    A directed edge in the topology graph connecting two stream nodes. Links carry data from the upstream node (`from`) to the downstream node (`to`) according to the specified delivery semantics. 
    """ # noqa: E501
    var_from: StrictInt = Field(description="ID of the upstream (producer) stream node.", alias="from", json_schema_extra={"examples": [1]})
    to: StrictInt = Field(description="ID of the downstream (consumer) stream node.", json_schema_extra={"examples": [2]})
    call_semantics: CallSemantics = Field(alias="callSemantics")
    var_async: Optional[StrictBool] = Field(default=None, description="Value returned by the caller's `IsAsync`/`isAsync` method when `callSemantics` is `FunctionCall`. Ignored for all other call semantics. ", alias="async")
    pool_name: Optional[StrictStr] = Field(default=None, description="Name of the worker pool to use when `callSemantics` is `TaskPool` or `PriorityTaskPool`. Must match a pool defined in `StreamApp.pools`. ", alias="poolName", json_schema_extra={"examples": ["default"]})
    priority: Optional[StrictInt] = Field(default=None, description="Message priority for `PriorityTaskPool` delivery. Higher values are processed first. Ignored for other call semantics. ")
    __properties: ClassVar[List[str]] = ["from", "to", "callSemantics", "async", "poolName", "priority"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Link from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Link from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "from": obj.get("from"),
            "to": obj.get("to"),
            "callSemantics": obj.get("callSemantics"),
            "async": obj.get("async"),
            "poolName": obj.get("poolName"),
            "priority": obj.get("priority")
        })
        return _obj


