# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ..models.call_semantics import CallSemantics
from ..models.environment import Environment
from ..models.log_level import LogLevel
from ..models.programming_language import ProgrammingLanguage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Service(BaseModel):
    """
    A single microservice in the topology. Each stream node belongs to exactly one service. The service defines the runtime configuration (ports, timeouts, logging) and the Go module path used for code generation. 
    """ # noqa: E501
    id: StrictInt = Field(description="Unique identifier for the service within the topology.", json_schema_extra={"examples": [1]})
    name: StrictStr = Field(description="Human-readable service name. Used as the root directory name for generated code.", json_schema_extra={"examples": ["ProcessingService"]})
    programming_language: ProgrammingLanguage = Field(alias="programmingLanguage")
    module_path: StrictStr = Field(description="Go module path (e.g. `github.com/example/myservice`). Used as the base import path for all generated packages within this service. ", alias="modulePath")
    golang_version: Optional[StrictStr] = Field(default=None, description="Minimum Go version required for the generated module (e.g. `1.22`).", alias="golangVersion")
    default_call_semantics: CallSemantics = Field(alias="defaultCallSemantics")
    http_host: StrictStr = Field(description="Host address for the service's HTTP server.", alias="httpHost")
    http_port: Annotated[int, Field(le=65535, strict=True, ge=0)] = Field(description="Port for the service's HTTP server.", alias="httpPort")
    status_handler: StrictStr = Field(description="URL path for the built-in topology visualization endpoint (e.g. `/status`). When set, the service serves a live dataflow graph with real-time call counts. Leave empty to disable. ", alias="statusHandler")
    metrics_handler: StrictStr = Field(description="URL path for the Prometheus metrics endpoint (e.g. `/metrics`). Leave empty to disable. ", alias="metricsHandler")
    grpc_host: StrictStr = Field(description="Host address for the service's gRPC server.", alias="grpcHost")
    grpc_port: Annotated[int, Field(le=65535, strict=True, ge=80)] = Field(description="Port for the service's gRPC server.", alias="grpcPort")
    default_grpc_timeout: Annotated[int, Field(strict=True, ge=0)] = Field(description="Default gRPC call timeout in milliseconds.", alias="defaultGrpcTimeout")
    color: StrictStr = Field(description="Hex color code used to represent this service in the visual topology designer.", json_schema_extra={"examples": ["#4A90D9"]})
    shutdown_timeout: Annotated[int, Field(strict=True, ge=0)] = Field(description="Maximum time in milliseconds to wait for graceful shutdown before forcing termination.", alias="shutdownTimeout")
    log_level: Optional[LogLevel] = Field(default=None, alias="logLevel")
    environment: Environment
    __properties: ClassVar[List[str]] = ["id", "name", "programmingLanguage", "modulePath", "golangVersion", "defaultCallSemantics", "httpHost", "httpPort", "statusHandler", "metricsHandler", "grpcHost", "grpcPort", "defaultGrpcTimeout", "color", "shutdownTimeout", "logLevel", "environment"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Service from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Service from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "programmingLanguage": obj.get("programmingLanguage"),
            "modulePath": obj.get("modulePath"),
            "golangVersion": obj.get("golangVersion"),
            "defaultCallSemantics": obj.get("defaultCallSemantics"),
            "httpHost": obj.get("httpHost"),
            "httpPort": obj.get("httpPort"),
            "statusHandler": obj.get("statusHandler"),
            "metricsHandler": obj.get("metricsHandler"),
            "grpcHost": obj.get("grpcHost"),
            "grpcPort": obj.get("grpcPort"),
            "defaultGrpcTimeout": obj.get("defaultGrpcTimeout"),
            "color": obj.get("color"),
            "shutdownTimeout": obj.get("shutdownTimeout"),
            "logLevel": obj.get("logLevel"),
            "environment": obj.get("environment")
        })
        return _obj


