# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from ..models.join_storage_type import JoinStorageType
from ..models.join_type import JoinType
from ..models.process_pattern import ProcessPattern
from ..models.transformation_type import TransformationType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Stream(BaseModel):
    """
    A node in the topology dataflow graph. Each stream node represents one operator (transformation, source, sink, or routing construct). The `type` field determines the operator and therefore the signature of the generated Go stub. 
    """ # noqa: E501
    id: StrictInt = Field(description="Unique identifier for this stream node within the topology.", json_schema_extra={"examples": [1]})
    name: StrictStr = Field(description="Human-readable node name shown in the visual designer.", json_schema_extra={"examples": ["HttpInputStream"]})
    id_source: Annotated[int, Field(strict=True, ge=0)] = Field(description="ID of the single upstream stream node. Used by operators with one input (Map, Filter, FlatMap, Process, KeyBy, Split, Case, Delay, Sink). Set to 0 when the node has no single source (Input nodes, Merge, MultiJoin). ", alias="idSource")
    id_sources: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="IDs of multiple upstream stream nodes. Used by Merge (same type, N sources) and MultiJoin (keyed streams, N sources). Mutually exclusive with `idSource` for these operator types. ", alias="idSources")
    type: TransformationType
    value_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Name of the output message type for this node (e.g. `OrderEvent`). Must match a type defined in `StreamApp.types` or an imported Go type. ", alias="valueType")
    key_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Name of the key type for keyed stream nodes (KeyBy, Join, MultiJoin). Must be a comparable Go type. ", alias="keyType")
    id_service: Annotated[int, Field(strict=True, ge=1)] = Field(description="ID of the service this node belongs to.", alias="idService")
    id_endpoint: Optional[StrictInt] = Field(default=None, description="ID of the associated endpoint. Required for Input and Sink nodes; determines which data connector entry/exit point this node uses. ", alias="idEndpoint")
    join_type: Optional[JoinType] = Field(default=None, alias="joinType")
    join_storage: Optional[JoinStorageType] = Field(default=None, alias="joinStorage")
    pattern: Optional[ProcessPattern] = None
    x_pos: Union[StrictFloat, StrictInt] = Field(description="Horizontal position of the node in the visual designer canvas.", alias="xPos")
    y_pos: Union[StrictFloat, StrictInt] = Field(description="Vertical position of the node in the visual designer canvas.", alias="yPos")
    function_name: Optional[StrictStr] = Field(default=None, description="Name of the generated Go struct for this node's business logic implementation. The code generator produces a stub with this name that the developer implements. ", alias="functionName")
    function_package: Optional[StrictStr] = Field(default=None, description="Subdirectory under the functions package where the generated stub is placed (e.g. `handlers`, `transforms`). Omit for the default functions package root. ", alias="functionPackage")
    public_function: Optional[StrictBool] = Field(default=None, description="When true, this node's stub is placed in the shared `pkg/functions` tree (or in a separate module if `functionModule` is set) and can be imported by other services. When false, it goes into the service's `internal/functions` tree. ", alias="publicFunction")
    function_description: Optional[StrictStr] = Field(default=None, description="Doc comment added to the generated struct. Describe the node's business purpose here.", alias="functionDescription")
    function_initializer_group: Optional[StrictStr] = Field(default=None, description="Initializer group name for dependency injection. Stubs in the same group are initialized together. Used by the generated service bootstrap code. ", alias="functionInitializerGroup")
    function_module: Optional[StrictStr] = Field(default=None, description="Name of a module defined in `StreamApp.modules`. When set (and `publicFunction: true`), the generated stub is placed in that module's package tree instead of the service module. Used to share business logic across multiple services. ", alias="functionModule")
    ttl: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Join state time-to-live in milliseconds. After this duration without a matching key from the other stream, the accumulated state is discarded. Applies to Join and MultiJoin. ")
    renew_ttl: Optional[StrictBool] = Field(default=None, description="When true, the TTL is reset each time a new element arrives for a key, keeping the state alive as long as data keeps flowing. Applies to Join and MultiJoin. ", alias="renewTTL")
    duration: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Fixed delay duration in milliseconds for the Delay operator. Used when the delay is not computed per-element. ")
    pipeline: Optional[StrictStr] = Field(default=None, description="Stream pipeline name ")
    __properties: ClassVar[List[str]] = ["id", "name", "idSource", "idSources", "type", "valueType", "keyType", "idService", "idEndpoint", "joinType", "joinStorage", "pattern", "xPos", "yPos", "functionName", "functionPackage", "publicFunction", "functionDescription", "functionInitializerGroup", "functionModule", "ttl", "renewTTL", "duration", "pipeline"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Stream from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Stream from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "idSource": obj.get("idSource"),
            "idSources": obj.get("idSources"),
            "type": obj.get("type"),
            "valueType": obj.get("valueType"),
            "keyType": obj.get("keyType"),
            "idService": obj.get("idService"),
            "idEndpoint": obj.get("idEndpoint"),
            "joinType": obj.get("joinType"),
            "joinStorage": obj.get("joinStorage"),
            "pattern": obj.get("pattern"),
            "xPos": obj.get("xPos"),
            "yPos": obj.get("yPos"),
            "functionName": obj.get("functionName"),
            "functionPackage": obj.get("functionPackage"),
            "publicFunction": obj.get("publicFunction"),
            "functionDescription": obj.get("functionDescription"),
            "functionInitializerGroup": obj.get("functionInitializerGroup"),
            "functionModule": obj.get("functionModule"),
            "ttl": obj.get("ttl"),
            "renewTTL": obj.get("renewTTL"),
            "duration": obj.get("duration"),
            "pipeline": obj.get("pipeline")
        })
        return _obj


