# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from ..models.data_connector import DataConnector
from ..models.endpoint import Endpoint
from ..models.link import Link
from ..models.module import Module
from ..models.pool import Pool
from ..models.project_settings import ProjectSettings
from ..models.service import Service
from ..models.stream import Stream
from ..models.type import Type
from ..models.undefined_enum import UndefinedEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StreamApp(BaseModel):
    """
    The complete topology definition for a distributed service system. This is the root document submitted to the code generator. It describes the full dataflow graph: which services exist, how streams connect, what external systems are involved, and what data types flow through the graph. 
    """ # noqa: E501
    settings: ProjectSettings
    streams: List[Stream] = Field(description="All stream nodes (operators) in the topology graph.")
    services: List[Service] = Field(description="Microservices that participate in the topology.")
    links: List[Link] = Field(description="Directed edges connecting stream nodes. Each link carries data from one node to the next.")
    types: List[Type] = Field(description="Named data types used as message types across the graph.")
    data_connectors: List[DataConnector] = Field(description="External system connections (HTTP servers, Kafka clusters, gRPC servers).", alias="dataConnectors")
    endpoints: List[Endpoint] = Field(description="Specific entry or exit points on a data connector (routes, topics, methods).")
    pools: List[Pool] = Field(description="Named worker pools used for async or priority-based stream delivery.")
    modules: Optional[List[Module]] = Field(default=None, description="Additional Go modules for shared public functions. When a stream or endpoint has `publicFunction: true` and references a module here via `functionModule`, generated stubs are placed in that module's package tree rather than the service's own module. ")
    undefined_enum: Optional[UndefinedEnum] = Field(default=None, alias="undefinedEnum")
    __properties: ClassVar[List[str]] = ["settings", "streams", "services", "links", "types", "dataConnectors", "endpoints", "pools", "modules", "undefinedEnum"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StreamApp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in streams (list)
        _items = []
        if self.streams:
            for _item_streams in self.streams:
                if _item_streams:
                    _items.append(_item_streams.to_dict())
            _dict['streams'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in services (list)
        _items = []
        if self.services:
            for _item_services in self.services:
                if _item_services:
                    _items.append(_item_services.to_dict())
            _dict['services'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item_links in self.links:
                if _item_links:
                    _items.append(_item_links.to_dict())
            _dict['links'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in types (list)
        _items = []
        if self.types:
            for _item_types in self.types:
                if _item_types:
                    _items.append(_item_types.to_dict())
            _dict['types'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in data_connectors (list)
        _items = []
        if self.data_connectors:
            for _item_data_connectors in self.data_connectors:
                if _item_data_connectors:
                    _items.append(_item_data_connectors.to_dict())
            _dict['dataConnectors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in endpoints (list)
        _items = []
        if self.endpoints:
            for _item_endpoints in self.endpoints:
                if _item_endpoints:
                    _items.append(_item_endpoints.to_dict())
            _dict['endpoints'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in pools (list)
        _items = []
        if self.pools:
            for _item_pools in self.pools:
                if _item_pools:
                    _items.append(_item_pools.to_dict())
            _dict['pools'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in modules (list)
        _items = []
        if self.modules:
            for _item_modules in self.modules:
                if _item_modules:
                    _items.append(_item_modules.to_dict())
            _dict['modules'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StreamApp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "settings": ProjectSettings.from_dict(obj["settings"]) if obj.get("settings") is not None else None,
            "streams": [Stream.from_dict(_item) for _item in obj["streams"]] if obj.get("streams") is not None else None,
            "services": [Service.from_dict(_item) for _item in obj["services"]] if obj.get("services") is not None else None,
            "links": [Link.from_dict(_item) for _item in obj["links"]] if obj.get("links") is not None else None,
            "types": [Type.from_dict(_item) for _item in obj["types"]] if obj.get("types") is not None else None,
            "dataConnectors": [DataConnector.from_dict(_item) for _item in obj["dataConnectors"]] if obj.get("dataConnectors") is not None else None,
            "endpoints": [Endpoint.from_dict(_item) for _item in obj["endpoints"]] if obj.get("endpoints") is not None else None,
            "pools": [Pool.from_dict(_item) for _item in obj["pools"]] if obj.get("pools") is not None else None,
            "modules": [Module.from_dict(_item) for _item in obj["modules"]] if obj.get("modules") is not None else None,
            "undefinedEnum": obj.get("undefinedEnum")
        })
        return _obj


