# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TransformationType(int, Enum):
    """
    The operator type for a stream node. Determines the node's role in the dataflow graph and the signature of the generated stub.  - `Input` (1): ingests data from an external source via a data connector endpoint - `Map` (2): transforms each element T → R - `Filter` (3): discards elements that do not satisfy a predicate - `Join` (4): combines two keyed streams (KeyValue[K,T1] + KeyValue[K,T2] → R) - `MultiJoin` (5): combines N keyed streams into a single output - `Process` (6): transforms T → R with a side-output error stream E - `FlatMap` (7): expands one element T into zero or more R - `FlatMapIterable` (8): expands T into an iterable of R without a user function - `KeyBy` (9): partitions a stream into keyed sub-streams (T → KeyValue[K,V]) - `Merge` (10): merges multiple streams of the same type T - `Split` (11): broadcasts one stream to multiple downstream consumers - `Case` (12): routes each element to one of N typed branches (switch/case) - `Sink` (13): sends data to an external destination via a data connector endpoint - `CycleLink` (14): feeds output back into an earlier node in the graph - `Error` (15): receives error elements from a Process node's error output - `Delay` (16): defers downstream delivery by a computed duration - `When` (17): a typed branch of a Case node 
    """

    """
    allowed enum values
    """
    Undefined = 0
    Input = 1
    Map = 2
    Filter = 3
    Join = 4
    MultiJoin = 5
    Process = 6
    FlatMap = 7
    FlatMapIterable = 8
    KeyBy = 9
    Merge = 10
    Split = 11
    Case = 12
    Sink = 13
    CycleLink = 14
    Error = 15
    Delay = 16
    When = 17

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransformationType from a JSON string"""
        return cls(json.loads(json_str))


