# coding: utf-8

"""
    Service Architect API

    Service Architect API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TransformationType(int, Enum):
    """
    TransformationType
    """

    """
    allowed enum values
    """
    Input = 1
    Map = 2
    Filter = 3
    Join = 4
    MultiJoin = 5
    ForEach = 6
    FlatMap = 7
    FlatMapIterable = 8
    KeyBy = 9
    Merge = 10
    Split = 11
    Parallels = 12
    Sink = 13
    AppSink = 14
    CycleLink = 15
    Delay = 16

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransformationType from a JSON string"""
        return cls(json.loads(json_str))


