# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TypeDefinitionFormat(int, Enum):
    """
    Serialization format used for the type definition. Determines how the type is serialized/deserialized when crossing process or network boundaries. - `Native` (1): language-native encoding (Go encoding/json, etc.) - `Protobuf` (2): Protocol Buffers - `FlatBuffers` (3): FlatBuffers - `CapNProto` (4): Cap'n Proto - `OpenAPI` (5): JSON encoding for types generated from an OpenAPI spec (oapi-codegen) 
    """

    """
    allowed enum values
    """
    Undefined = 0
    Native = 1
    Protobuf = 2
    FlatBuffers = 3
    CapNProto = 4
    OpenAPI = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TypeDefinitionFormat from a JSON string"""
        return cls(json.loads(json_str))


