# coding: utf-8

"""
    Service Topology Runtime — Code Generation API

    API for the **GoRunDebug** code generator (`servicegen`).  A client submits a complete `StreamApp` topology definition — services, streams, data connectors, endpoints, types, and links — and receives a ZIP archive containing ready-to-compile Go stubs for every node in the graph.  The topology definition is the source of truth. It drives both the visual representation in the GoRunDebug designer and the runtime behavior of the generated service. Developers implement only the generated stubs; all infrastructure plumbing is handled by the `servicelib` runtime. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ..models.data_type import DataType
from ..models.type_definition_format import TypeDefinitionFormat
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Type(BaseModel):
    """
    A named data type used as a message type in the topology graph. Types are referenced by stream nodes via `valueType` and `keyType`. The code generator uses the type definition to produce correct Go type references and import statements in generated stubs. 
    """ # noqa: E501
    name: StrictStr = Field(description="Unique type name referenced by streams (e.g. `OrderEvent`, `UserProfile`).", json_schema_extra={"examples": ["OrderEvent"]})
    description: Optional[StrictStr] = Field(default=None, description="Human-readable description of this type. Used as a doc comment in generated code.")
    type: DataType
    value_type: Optional[StrictStr] = Field(default=None, description="Element type for `array` and value type for `map` composite types.", alias="valueType")
    key_type: Optional[StrictStr] = Field(default=None, description="Key type for `map` composite types.", alias="keyType")
    definition_format: Optional[TypeDefinitionFormat] = Field(default=None, alias="definitionFormat")
    transfer_by_value: Optional[StrictBool] = Field(default=None, description="When true, the type is passed by value in generated function signatures. When false (default), it is passed as a pointer. ", alias="transferByValue", json_schema_extra={"examples": [False]})
    use_alias: Optional[StrictBool] = Field(default=None, description="When true, the generated Go code uses a type alias instead of a full struct definition.", alias="useAlias")
    type_definition_lang1: Optional[StrictStr] = Field(default=None, description="Inline type definition for GoLang (e.g. `interface{}`, `map[string]int`). Used when the type has no external package.", alias="typeDefinitionLang1", json_schema_extra={"examples": ["interface{}"]})
    type_definition_lang2: Optional[StrictStr] = Field(default=None, description="Inline type definition for C++ (e.g. `std::any`).", alias="typeDefinitionLang2", json_schema_extra={"examples": ["std::any"]})
    type_import_lang1: Optional[StrictStr] = Field(default=None, description="Go import path for the package that defines this type (e.g. `github.com/example/types`).", alias="typeImportLang1")
    type_import_lang2: Optional[StrictStr] = Field(default=None, description="C++ include path for the header that defines this type.", alias="typeImportLang2")
    package: Optional[StrictStr] = Field(default=None, description="Go package name alias used in generated import statements when it differs from the last path component.")
    public_type: Optional[StrictBool] = Field(default=None, description="When true, this type is shared across services and placed in the shared types package.", alias="publicType")
    module: Optional[StrictStr] = Field(default=None, description="Name of a module defined in `StreamApp.modules` that owns this type. Used to resolve the correct import path when `publicType: true`. ")
    __properties: ClassVar[List[str]] = ["name", "description", "type", "valueType", "keyType", "definitionFormat", "transferByValue", "useAlias", "typeDefinitionLang1", "typeDefinitionLang2", "typeImportLang1", "typeImportLang2", "package", "publicType", "module"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Type from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Type from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "type": obj.get("type"),
            "valueType": obj.get("valueType"),
            "keyType": obj.get("keyType"),
            "definitionFormat": obj.get("definitionFormat"),
            "transferByValue": obj.get("transferByValue"),
            "useAlias": obj.get("useAlias"),
            "typeDefinitionLang1": obj.get("typeDefinitionLang1"),
            "typeDefinitionLang2": obj.get("typeDefinitionLang2"),
            "typeImportLang1": obj.get("typeImportLang1"),
            "typeImportLang2": obj.get("typeImportLang2"),
            "package": obj.get("package"),
            "publicType": obj.get("publicType"),
            "module": obj.get("module")
        })
        return _obj


