# coding: utf-8

"""
    Service Architect API

    Service Architect API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DataType(str, Enum):
    """
    DataType
    """

    """
    allowed enum values
    """
    INT = 'int'
    UINT = 'uint'
    BYTE = 'byte'
    CHAR = 'char'
    BOOLEAN = 'boolean'
    UNICODE_CHAR = 'unicode char'
    STRING = 'string'
    UNICODE_STRING = 'unicode string'
    FLOAT = 'float'
    DOUBLE = 'double'
    INT8 = 'int8'
    INT16 = 'int16'
    INT32 = 'int32'
    INT64 = 'int64'
    UINT8 = 'uint8'
    UINT16 = 'uint16'
    UINT32 = 'uint32'
    UINT64 = 'uint64'
    ARRAY = 'array'
    MAP = 'map'
    STRUCT = 'struct'
    CUSTOM = 'custom'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataType from a JSON string"""
        return cls(json.loads(json_str))


