# coding: utf-8

"""
    Service Architect API

    Service Architect API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class JoinType(int, Enum):
    """
    JoinType
    """

    """
    allowed enum values
    """
    Inner = 1
    Left = 2
    Right = 3
    Outer = 4

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JoinType from a JSON string"""
        return cls(json.loads(json_str))


