# coding: utf-8

"""
    Service Architect API

    Service Architect API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ..models.call_semantics import CallSemantics
from ..models.communication_protocol import CommunicationProtocol
from typing import Optional, Set
from typing_extensions import Self

class Link(BaseModel):
    """
    Link
    """ # noqa: E501
    var_from: StrictInt = Field(alias="from")
    to: StrictInt
    call_semantics: CallSemantics = Field(alias="callSemantics")
    income_call_semantics: Optional[CallSemantics] = Field(default=None, alias="incomeCallSemantics")
    inherited_call_semantics: StrictBool = Field(alias="inheritedCallSemantics")
    income_inherited_call_semantics: Optional[StrictBool] = Field(default=None, alias="incomeInheritedCallSemantics")
    pool_name: Optional[StrictStr] = Field(default=None, alias="poolName")
    income_pool_name: Optional[StrictStr] = Field(default=None, alias="incomePoolName")
    priority: Optional[StrictInt] = None
    income_priority: Optional[StrictInt] = Field(default=None, alias="incomePriority")
    method_name: Optional[StrictStr] = Field(default=None, alias="methodName")
    timeout: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    communication_protocol: Optional[CommunicationProtocol] = Field(default=None, alias="communicationProtocol")
    __properties: ClassVar[List[str]] = ["from", "to", "callSemantics", "incomeCallSemantics", "inheritedCallSemantics", "incomeInheritedCallSemantics", "poolName", "incomePoolName", "priority", "incomePriority", "methodName", "timeout", "communicationProtocol"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Link from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Link from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "from": obj.get("from"),
            "to": obj.get("to"),
            "callSemantics": obj.get("callSemantics"),
            "incomeCallSemantics": obj.get("incomeCallSemantics"),
            "inheritedCallSemantics": obj.get("inheritedCallSemantics"),
            "incomeInheritedCallSemantics": obj.get("incomeInheritedCallSemantics"),
            "poolName": obj.get("poolName"),
            "incomePoolName": obj.get("incomePoolName"),
            "priority": obj.get("priority"),
            "incomePriority": obj.get("incomePriority"),
            "methodName": obj.get("methodName"),
            "timeout": obj.get("timeout"),
            "communicationProtocol": obj.get("communicationProtocol")
        })
        return _obj


