settings:
  name: Example
  moduleVersion: v0.1.0
  repoPath: pyservicelib/example

services:
  inventoryService:
    id: 1
    name: Inventory Service
    programmingLanguage: 3
    modulePath: inventoryservice
    defaultCallSemantics: 2
    httpHost: 0.0.0.0
    httpPort: 9092
    statusHandler: status
    metricsHandler: metrics
    grpcHost: 0.0.0.0
    grpcPort: 9202
    defaultGrpcTimeout: 5000
    color: "#D2E5FF"
    shutdownTimeout: 30000
    environment: local

streams:
  getInventoryItemData:
    {id: 1, name: Get Inventory Item Data, idSource: 3, type: 6, valueType: OrderItemResult, idService: 1, xPos: 400, yPos: -261, pipeline: inventoryItem}
  mergeInventoryResult:
    {id: 2, name: Merge Inventory Result, idSource: 0, idSources: [1], type: 10, idService: 1, xPos: 542, yPos: 33, pipeline: inventoryItem}
  processInventoryItem:
    {id: 3, name: Process Inventory Item, idSource: 2, type: 1, valueType: OrderItem, idService: 1, idEndpoint: 1, xPos: 131, yPos: -165, pipeline: inventoryItem}

links:
  inputToProcess: {from: 3, to: 1, callSemantics: 2}
  processToMerge: {from: 1, to: 2, callSemantics: 2}
  mergeToInput: {from: 2, to: 3, callSemantics: 2}

dataConnectors:
  inventoryServiceApi:
    id: 1
    name: Inventory Service API
    type: 2
    implementation: google/grpc
    host: 0.0.0.0
    port: 9202
    address: 0.0.0.0:9202

endpoints:
  processOrderItem:
    id: 1
    name: Process Order Item
    idDataConnector: 1
    grpcMethodType: 1
    methodName: ProcessOrderItem

types:
  orderItem: {name: OrderItem, type: struct, definitionFormat: 1, transferByValue: false}
  orderItemResult: {name: OrderItemResult, type: struct, definitionFormat: 1, transferByValue: false}

pools: {}
