"""Code generated by servicegen. DO NOT EDIT."""

from typing import Any

from example_model import OrderItem, OrderItemResult
from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.datasource.grpc.grpcds import (
    make_grpc_no_streaming_endpoint_consumer,
)
from pyservicelib_gorundebug.runtime.common import Consumer
from pyservicelib_gorundebug.runtime.context import Context
from datetime import timedelta

from pyservicelib_gorundebug.runtime.serviceapp import (
    ServiceApp,
    run_shutdown_operations,
)

from ..functions import GetInventoryItemData, ProcessOrderItem
from ..config import Config
from .grpc_service_generated import GrpcServer


class GeneratedService(ServiceApp):
    """Generated topology/bootstrap. Regeneration may overwrite this file."""

    def __init__(self) -> None:
        super().__init__()
        self._transport_consumers: list[Consumer[Any]] = []
        self._makers: dict[str, Any] = {
            "get_inventory_item_data": GetInventoryItemData,
            "process_order_item": ProcessOrderItem,
        }
        self._functions: dict[str, Any] = {}

    async def custom_makers_init(self, ctx: Context) -> None:
        """User hook: override entries in ``_makers`` before construction."""
        del ctx

    async def custom_functions_init(self, ctx: Context) -> None:
        """User hook: configure constructed functions before graph wiring."""
        del ctx

    async def on_start(self, ctx: Context) -> None:
        """User hook called after graph construction and before runtime start."""
        del ctx

    async def on_stop(self, ctx: Context) -> None:
        """User hook called before generated shutdown."""
        del ctx

    async def build_runtime(self, ctx: Context) -> None:
        await self.custom_makers_init(ctx)
        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "inventory service requires inventoryservice.internal.config.Config"
            )
        named = cfg.named
        input_cfg = named.streams.process_inventory_item
        process_cfg = named.streams.get_inventory_item_data
        merge_cfg = named.streams.merge_inventory_result
        self._functions = {
            "get_inventory_item_data": self._makers[
                "get_inventory_item_data"
            ](),
            "process_order_item": self._makers["process_order_item"](),
        }
        await self.custom_functions_init(ctx)

        input_stream = transformation.Input[
            OrderItem, OrderItemResult, Exception
        ](input_cfg, self)
        processed = transformation.Process[
            OrderItem, OrderItemResult, OrderItemResult
        ](process_cfg, input_stream, self._functions["get_inventory_item_data"])
        merged = transformation.Merge[OrderItemResult](
            merge_cfg,
            processed,
            processed.error_stream,
        )
        input_stream.set_source(merged)

        consumer, handler = make_grpc_no_streaming_endpoint_consumer(
            input_stream, self._functions["process_order_item"]
        )
        self._transport_consumers.append(consumer)
        service_cfg = self.service_config
        self.add_component(
            GrpcServer(service_cfg.grpc_host, service_cfg.grpc_port, handler)
        )

    async def start_service(self, ctx: Context) -> None:
        await self.build_runtime(ctx)
        await self.on_start(ctx)
        await self.start(ctx)

    async def stop_service(self, ctx: Context) -> None:
        ctx = ctx.bounded(
            timedelta(milliseconds=self.service_config.shutdown_timeout)
        )
        await run_shutdown_operations(
            self.log,
            ctx,
            [
                ("user_on_stop", self.on_stop(ctx)),
                ("service_runtime", self.stop(ctx)),
            ],
        )
