"""Code generated by servicegen. DO NOT EDIT."""

from datetime import timedelta
from typing import Any

import grpc
from example_model import OrderItem, OrderItemResult
from inventory_service_api.generated import processorderitem_pb2, processorderitem_pb2_grpc
from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.datasink.grpc.grpcds import (
    make_grpc_no_streaming_endpoint_consumer,
)
from pyservicelib_gorundebug.runtime.common import Consumer
from pyservicelib_gorundebug.runtime.context import Context
from pyservicelib_gorundebug.runtime.serviceapp import (
    ServiceApp,
    run_shutdown_operations,
)

from ..functions import (
    MapOrderItemResultToOrderState,
    MapToOrderState,
    ProcessOrder,
    ProcessOrderItemSink,
    ProcessOrderItems,
    SoftDeadline,
)
from ..config import Config
from ..types import Order, OrderState
from .http_service_generated import make_process_order_http_consumer


class GeneratedService(ServiceApp):
    """Generated topology/bootstrap. Regeneration may overwrite this file."""

    def __init__(self) -> None:
        super().__init__()
        self._channel: grpc.aio.Channel | None = None
        self._transport_consumers: list[Consumer[Any]] = []
        self._makers: dict[str, Any] = {
            "process_order_items": ProcessOrderItems,
            "map_item_result": MapOrderItemResultToOrderState,
            "map_timeout": MapToOrderState,
            "soft_deadline": SoftDeadline,
            "process_order": ProcessOrder,
            "process_order_item_sink": ProcessOrderItemSink,
        }
        self._functions: dict[str, Any] = {}

    async def custom_makers_init(self, ctx: Context) -> None:
        """User hook: override entries in ``_makers`` before construction."""
        del ctx

    async def custom_functions_init(self, ctx: Context) -> None:
        """User hook: configure constructed functions before graph wiring."""
        del ctx

    async def on_start(self, ctx: Context) -> None:
        """User hook called after graph construction and before runtime start."""
        del ctx

    async def on_stop(self, ctx: Context) -> None:
        """User hook called before generated shutdown."""
        del ctx

    async def build_runtime(self, ctx: Context) -> None:
        await self.custom_makers_init(ctx)
        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError("order service requires orderservice.internal.config.Config")
        named = cfg.named
        input_cfg = named.streams.process_order
        split_cfg = named.streams.split_pipeline
        items_cfg = named.streams.process_order_items
        sink_cfg = named.streams.process_order_item
        item_state_cfg = named.streams.map_order_item_result_to_order_state
        delay_cfg = named.streams.soft_deadline
        timeout_state_cfg = named.streams.map_to_order_state
        merge_cfg = named.streams.merge_results
        timeout = timedelta(
            milliseconds=_int_property(
                named.endpoints.process_order.properties,
                "timeout",
                default=5000,
            )
        )
        self._functions = {
            "process_order_items": self._makers["process_order_items"](),
            "map_item_result": self._makers["map_item_result"](),
            "map_timeout": self._makers["map_timeout"](),
            "soft_deadline": self._makers["soft_deadline"](
                timedelta(milliseconds=delay_cfg.raw_config.duration or 0)
            ),
            "process_order": self._makers["process_order"](timeout),
            "process_order_item_sink": self._makers[
                "process_order_item_sink"
            ](),
        }
        await self.custom_functions_init(ctx)

        input_stream = transformation.Input[Order, OrderState, Exception](input_cfg, self)
        split = transformation.Split[Order](split_cfg, input_stream)

        items = transformation.FlatMap[Order, OrderItem](
            items_cfg,
            split.add_stream(),
            self._functions["process_order_items"],
        )
        item_sink = transformation.SinkWithResult[
            OrderItem, OrderItemResult, Exception
        ](sink_cfg, items)
        item_states = transformation.Map[OrderItemResult, OrderState](
            item_state_cfg,
            item_sink,
            self._functions["map_item_result"],
        )

        delayed = transformation.Delay[Order](
            delay_cfg,
            split.add_stream(),
            self._functions["soft_deadline"],
        )
        timeout_states = transformation.Map[Order, OrderState](
            timeout_state_cfg,
            delayed,
            self._functions["map_timeout"],
        )
        merged = transformation.Merge[OrderState](merge_cfg, timeout_states, item_states)
        input_stream.set_source(merged)

        connector_cfg = named.data_connectors.inventory_service_api
        self._channel = grpc.aio.insecure_channel(
            _required(
                connector_cfg.address,
                "Inventory Service API connector address",
            )
        )
        stub = processorderitem_pb2_grpc.InventoryServiceApiStub(self._channel)
        grpc_consumer = make_grpc_no_streaming_endpoint_consumer(
            item_sink,
            self._functions["process_order_item_sink"],
            stub.ProcessOrderItem,
        )
        self._transport_consumers.append(grpc_consumer)

        http_consumer = make_process_order_http_consumer(
            input_stream,
            self._functions["process_order"],
        )
        self._transport_consumers.append(http_consumer)

    async def start_service(self, ctx: Context) -> None:
        await self.build_runtime(ctx)
        await self.on_start(ctx)
        await self.start(ctx)

    async def stop_service(self, ctx: Context) -> None:
        ctx = ctx.bounded(
            timedelta(milliseconds=self.service_config.shutdown_timeout)
        )

        async def close_grpc_channel() -> None:
            if self._channel is None:
                return
            await self._channel.close(grace=None)
            self._channel = None

        await run_shutdown_operations(
            self.log,
            ctx,
            [
                ("user_on_stop", self.on_stop(ctx)),
                ("service_runtime", self.stop(ctx)),
                (
                    "grpc_channel:inventory_service_api",
                    close_grpc_channel(),
                ),
            ],
        )


def _required[T](value: T | None, label: str) -> T:
    if value is None:
        raise ValueError(f"{label} is required")
    return value


def _int_property(
    properties: dict[str, Any] | None,
    name: str,
    *,
    default: int,
) -> int:
    if properties is None or name not in properties:
        return default
    value = properties[name]
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"endpoint property '{name}' must be an integer")
    return value
