[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "servicelib-example-orderservice"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "grpcio>=1.81.0",
  "pyservicelib-gorundebug",
  "servicelib-example-inventory-service-api",
  "servicelib-example-model",
  "servicelib-example-order-service-api",
]

[project.scripts]
example-orderservice = "orderservice.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/orderservice"]
