# coding: utf-8

"""
    Service Architect API

    Service Architect API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyservicelib.api.models.data_format import DataFormat
from typing import Optional, Set
from typing_extensions import Self

class Endpoint(BaseModel):
    """
    Endpoint
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    id_data_connector: StrictInt = Field(alias="idDataConnector")
    method: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    format: Optional[DataFormat] = None
    param: Optional[StrictStr] = None
    function_name: Optional[StrictStr] = Field(default=None, alias="functionName")
    function_package: Optional[StrictStr] = Field(default=None, alias="functionPackage")
    public_function: Optional[StrictBool] = Field(default=None, alias="publicFunction")
    function_description: Optional[StrictStr] = Field(default=None, alias="functionDescription")
    delay: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["id", "name", "idDataConnector", "method", "path", "format", "param", "functionName", "functionPackage", "publicFunction", "functionDescription", "delay"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Endpoint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Endpoint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "idDataConnector": obj.get("idDataConnector"),
            "method": obj.get("method"),
            "path": obj.get("path"),
            "format": obj.get("format"),
            "param": obj.get("param"),
            "functionName": obj.get("functionName"),
            "functionPackage": obj.get("functionPackage"),
            "publicFunction": obj.get("publicFunction"),
            "functionDescription": obj.get("functionDescription"),
            "delay": obj.get("delay")
        })
        return _obj


