# coding: utf-8

"""
    Service Architect API

    Service Architect API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from pyservicelib.api.models.call_semantics import CallSemantics
from pyservicelib.api.models.log_level import LogLevel
from pyservicelib.api.models.programming_language import ProgrammingLanguage
from typing import Optional, Set
from typing_extensions import Self

class Service(BaseModel):
    """
    Service
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    programming_language: ProgrammingLanguage = Field(alias="programmingLanguage")
    default_call_semantics: CallSemantics = Field(alias="defaultCallSemantics")
    monitoring_port: Annotated[int, Field(le=65535, strict=True, ge=80)] = Field(alias="monitoringPort")
    monitoring_host: StrictStr = Field(alias="monitoringHost")
    grpc_port: Annotated[int, Field(le=65535, strict=True, ge=80)] = Field(alias="grpcPort")
    default_grpc_timeout: Annotated[int, Field(strict=True, ge=0)] = Field(alias="defaultGrpcTimeout")
    grpc_host: StrictStr = Field(alias="grpcHost")
    color: StrictStr
    shutdown_timeout: Annotated[int, Field(strict=True, ge=0)] = Field(alias="shutdownTimeout")
    log_level: Optional[LogLevel] = Field(default=None, alias="logLevel")
    environment: StrictStr
    delay_executors: Annotated[int, Field(strict=True, ge=1)] = Field(alias="delayExecutors")
    __properties: ClassVar[List[str]] = ["id", "name", "programmingLanguage", "defaultCallSemantics", "monitoringPort", "monitoringHost", "grpcPort", "defaultGrpcTimeout", "grpcHost", "color", "shutdownTimeout", "logLevel", "environment", "delayExecutors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Service from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Service from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "programmingLanguage": obj.get("programmingLanguage"),
            "defaultCallSemantics": obj.get("defaultCallSemantics"),
            "monitoringPort": obj.get("monitoringPort"),
            "monitoringHost": obj.get("monitoringHost"),
            "grpcPort": obj.get("grpcPort"),
            "defaultGrpcTimeout": obj.get("defaultGrpcTimeout"),
            "grpcHost": obj.get("grpcHost"),
            "color": obj.get("color"),
            "shutdownTimeout": obj.get("shutdownTimeout"),
            "logLevel": obj.get("logLevel"),
            "environment": obj.get("environment"),
            "delayExecutors": obj.get("delayExecutors")
        })
        return _obj


