# coding: utf-8

"""
    Service Architect API

    Service Architect API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pyservicelib.api.models.join_storage_type import JoinStorageType
from pyservicelib.api.models.join_type import JoinType
from pyservicelib.api.models.transformation_type import TransformationType
from typing import Optional, Set
from typing_extensions import Self

class Stream(BaseModel):
    """
    Stream
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    id_source: Annotated[int, Field(strict=True, ge=0)] = Field(alias="idSource")
    id_sources: List[Annotated[int, Field(strict=True, ge=1)]] = Field(alias="idSources")
    type: TransformationType
    value_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="valueType")
    key_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="keyType")
    id_service: Annotated[int, Field(strict=True, ge=1)] = Field(alias="idService")
    id_endpoint: Optional[StrictInt] = Field(default=None, alias="idEndpoint")
    join_type: Optional[JoinType] = Field(default=None, alias="joinType")
    join_storage: Optional[JoinStorageType] = Field(default=None, alias="joinStorage")
    x_pos: StrictInt = Field(alias="xPos")
    y_pos: StrictInt = Field(alias="yPos")
    function_name: Optional[StrictStr] = Field(default=None, alias="functionName")
    function_package: Optional[StrictStr] = Field(default=None, alias="functionPackage")
    public_function: Optional[StrictBool] = Field(default=None, alias="publicFunction")
    function_description: Optional[StrictStr] = Field(default=None, alias="functionDescription")
    ttl: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    renew_ttl: Optional[StrictBool] = Field(default=None, alias="renewTTL")
    duration: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "idSource", "idSources", "type", "valueType", "keyType", "idService", "idEndpoint", "joinType", "joinStorage", "xPos", "yPos", "functionName", "functionPackage", "publicFunction", "functionDescription", "ttl", "renewTTL", "duration"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Stream from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Stream from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "idSource": obj.get("idSource"),
            "idSources": obj.get("idSources"),
            "type": obj.get("type"),
            "valueType": obj.get("valueType"),
            "keyType": obj.get("keyType"),
            "idService": obj.get("idService"),
            "idEndpoint": obj.get("idEndpoint"),
            "joinType": obj.get("joinType"),
            "joinStorage": obj.get("joinStorage"),
            "xPos": obj.get("xPos"),
            "yPos": obj.get("yPos"),
            "functionName": obj.get("functionName"),
            "functionPackage": obj.get("functionPackage"),
            "publicFunction": obj.get("publicFunction"),
            "functionDescription": obj.get("functionDescription"),
            "ttl": obj.get("ttl"),
            "renewTTL": obj.get("renewTTL"),
            "duration": obj.get("duration")
        })
        return _obj


