# coding: utf-8

"""
    Service Architect API

    Service Architect API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from pyservicelib.api.models.data_type import DataType
from pyservicelib.api.models.type_definition_format import TypeDefinitionFormat
from typing import Optional, Set
from typing_extensions import Self

class Type(BaseModel):
    """
    Type
    """ # noqa: E501
    name: StrictStr
    type: DataType
    value_type: Optional[StrictStr] = Field(default=None, alias="valueType")
    key_type: Optional[StrictStr] = Field(default=None, alias="keyType")
    definition_format: Optional[TypeDefinitionFormat] = Field(default=None, alias="definitionFormat")
    transfer_by_value: Optional[StrictBool] = Field(default=None, alias="transferByValue")
    use_alias: Optional[StrictBool] = Field(default=None, alias="useAlias")
    type_definition_lang1: Optional[StrictStr] = Field(default=None, alias="typeDefinitionLang1")
    type_definition_lang2: Optional[StrictStr] = Field(default=None, alias="typeDefinitionLang2")
    type_import_lang1: Optional[StrictStr] = Field(default=None, alias="typeImportLang1")
    type_import_lang2: Optional[StrictStr] = Field(default=None, alias="typeImportLang2")
    package: Optional[StrictStr] = None
    public_type: Optional[StrictBool] = Field(default=None, alias="publicType")
    __properties: ClassVar[List[str]] = ["name", "type", "valueType", "keyType", "definitionFormat", "transferByValue", "useAlias", "typeDefinitionLang1", "typeDefinitionLang2", "typeImportLang1", "typeImportLang2", "package", "publicType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Type from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Type from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "valueType": obj.get("valueType"),
            "keyType": obj.get("keyType"),
            "definitionFormat": obj.get("definitionFormat"),
            "transferByValue": obj.get("transferByValue"),
            "useAlias": obj.get("useAlias"),
            "typeDefinitionLang1": obj.get("typeDefinitionLang1"),
            "typeDefinitionLang2": obj.get("typeDefinitionLang2"),
            "typeImportLang1": obj.get("typeImportLang1"),
            "typeImportLang2": obj.get("typeImportLang2"),
            "package": obj.get("package"),
            "publicType": obj.get("publicType")
        })
        return _obj


