"""Code generated by servicegen. DO NOT EDIT."""

from dataclasses import dataclass
from typing import Any

from pyservicelib_gorundebug.runtime.config import (
    DataConnectorConfig,
    DelayStreamConfig,
    EndpointConfig,
    FlatMapStreamConfig,
    InputStreamConfig,
    MapStreamConfig,
    MergeStreamConfig,
    ServiceAppConfig,
    ServiceConfig,
    SinkStreamConfig,
    SplitStreamConfig,
)


@dataclass(frozen=True, slots=True)
class Streams:
    map_order_item_result_to_order_state: MapStreamConfig
    map_to_order_state: MapStreamConfig
    merge_results: MergeStreamConfig
    process_order: InputStreamConfig
    process_order_item: SinkStreamConfig
    process_order_items: FlatMapStreamConfig
    soft_deadline: DelayStreamConfig
    split_pipeline: SplitStreamConfig


@dataclass(frozen=True, slots=True)
class Endpoints:
    process_order: EndpointConfig
    process_order_item: EndpointConfig


@dataclass(frozen=True, slots=True)
class DataConnectors:
    inventory_service_api: DataConnectorConfig
    order_service_api: DataConnectorConfig


@dataclass(frozen=True, slots=True)
class Services:
    order_service: ServiceConfig


@dataclass(frozen=True, slots=True)
class NamedConfig:
    streams: Streams
    endpoints: Endpoints
    data_connectors: DataConnectors
    services: Services


class GeneratedConfig(ServiceAppConfig):
    """Generated, typed view over the generic runtime graph configuration."""

    @classmethod
    def _load_config(cls, obj: dict[str, Any]) -> dict[str, Any]:
        def values(name: str) -> list[dict[str, Any]]:
            section = obj.get(name, {})
            return list(section.values()) if isinstance(section, dict) else section

        normalized = dict(obj)
        for name in ("services", "streams", "links", "types", "pools", "endpoints"):
            normalized[name] = values(name)
        normalized["dataConnectors"] = values("dataConnectors")
        return super()._load_config(normalized)

    @property
    def named(self) -> NamedConfig:
        return NamedConfig(
            streams=Streams(
                map_order_item_result_to_order_state=MapStreamConfig(
                    self.get_stream_config_by_id(1)
                ),
                map_to_order_state=MapStreamConfig(
                    self.get_stream_config_by_id(2)
                ),
                merge_results=MergeStreamConfig(
                    self.get_stream_config_by_id(3)
                ),
                process_order=InputStreamConfig(
                    self.get_stream_config_by_id(4)
                ),
                process_order_item=SinkStreamConfig(
                    self.get_stream_config_by_id(5)
                ),
                process_order_items=FlatMapStreamConfig(
                    self.get_stream_config_by_id(6)
                ),
                soft_deadline=DelayStreamConfig(
                    self.get_stream_config_by_id(7)
                ),
                split_pipeline=SplitStreamConfig(
                    self.get_stream_config_by_id(8)
                ),
            ),
            endpoints=Endpoints(
                process_order=self.get_endpoint_config_by_id(1),
                process_order_item=self.get_endpoint_config_by_id(2),
            ),
            data_connectors=DataConnectors(
                inventory_service_api=self.get_data_connector_by_id(1),
                order_service_api=self.get_data_connector_by_id(2),
            ),
            services=Services(
                order_service=self.get_service_config_by_id(1),
            ),
        )
